CREATE TABLE Ta(AID INT PRIMARY KEY, a2 INT UNIQUE, a3 INT, a4 INT)
CREATE TABLE Tb(BID INT PRIMARY KEY, b2 INT, b3 INT, b4 INT)
CREATE TABLE Tc(CID INT PRIMARY KEY, AID INT REFERENCES Ta(AID), BID INT REFERENCES Tb(BID), c1 INT, c2 INT)

DROP TABLE Ta
DROP TABLE Tb
DROP TABLE Tc

--a

--clustered index scan
SELECT T.a3
FROM Ta T

--clustered index seek
SELECT T.AID
FROM Ta T
WHERE T.AID > 0

--nonclustered index scan
SELECT T.AID
FROM Ta T

--nonclustered index seek
SELECT T.a2
FROM Ta T
WHERE T.a2 = 1

--key lookup
SELECT T.AID, T.a2, T.a4
FROM Ta T
WHERE T.a2 = 0

EXEC sp_helpindex Ta

INSERT INTO Ta VALUES(1,4,3,4)
INSERT INTO Ta VALUES(2,3,3,4)
INSERT INTO Ta VALUES(3,2,3,4)
INSERT INTO Ta VALUES(4,1,3,4)

--b
DECLARE @i INT
SET @i = 1
WHILE @i<=1000
BEGIN
	INSERT INTO Tb VALUES(@i,@i,@i,@i)
	SET @i = @i +1
END
SELECT COUNT(*) FROM Tb
DELETE FROM Tb
DELETE FROM Tc

SELECT T.BID
FROM Tb T
WHERE T.b2 >= 500

CREATE NONCLUSTERED 
INDEX index_b2
ON Tb ( b2 DESC )

DROP INDEX index_b2 ON Tb

GO

--c
CREATE OR ALTER VIEW vJoint
AS
	SELECT Tb.b2, Tc.c1, Ta.a3
	FROM Tb INNER JOIN Tc ON Tb.BID = Tc.BID INNER JOIN Ta ON Ta.AID = Tc.AID
	WHERE Tb.b2 >= 2

GO

INSERT INTO Tc VALUES(1,4,1,4,8)
INSERT INTO Tc VALUES(2,3,2,4,9)
INSERT INTO Tc VALUES(3,2,3,4,5)
INSERT INTO Tc VALUES(4,1,4,4,0)

SELECT* FROM vJoint